# Generated by Django 5.1.7 on 2025-03-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DebitCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('phone', models.PositiveIntegerField(max_length=12, unique=True)),
                ('national_id', models.IntegerField(unique=True)),
                ('age', models.PositiveIntegerField(default=18)),
            ],
        ),
    ]
