# Generated by Django 5.1.7 on 2025-03-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debitcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitcart',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
